# Generated by Django 5.1.3 on 2024-12-23 15:48

import apps.Divider.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Divider', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagemodel',
            name='img',
            field=models.ImageField(upload_to=apps.Divider.models.upload_to),
        ),
    ]
